server:
  port : 8081
spring:
  application:
   name: BILL-SERVICE
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/billfoldbillservicedb
    username: root
    password: root#123
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
        import: configserver:http://localhost:9296