name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Test Backend
        working-directory: backend
        run: |
          ./mvnw clean install

      - name: Build and Test Frontend
        working-directory: frontend
        run: |
          npm install
          npm test

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Production
        
